"""initial

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('level_rates',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('level')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'boss', 'admin', 'guide', 'driver', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('boss_admins',
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['boss_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('boss_id', 'admin_id')
    )
    op.create_table('boss_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('super_admin_percent', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('driver_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_model', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('guide_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('completed_tours', sa.Integer(), nullable=False),
    sa.Column('level_tours', sa.Integer(), nullable=False),
    sa.Column('practice_done', sa.Boolean(), nullable=False),
    sa.Column('interview_passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tours_count', sa.Integer(), nullable=False),
    sa.Column('gross', sa.Integer(), nullable=False),
    sa.Column('fines_total', sa.Integer(), nullable=False),
    sa.Column('net', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('paid_by_boss', 'confirmed', name='paystatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_boss_id'), 'payments', ['boss_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pickup_address', sa.String(length=255), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('price_original', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('usd_rate_used', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('platform_percent', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('guide_amount', sa.Integer(), nullable=False),
    sa.Column('driver_amount', sa.Integer(), nullable=False),
    sa.Column('guide_note', sa.Text(), nullable=False),
    sa.Column('driver_note', sa.Text(), nullable=False),
    sa.Column('min_guide_level', sa.Integer(), nullable=True),
    sa.Column('tourist_name', sa.String(length=120), nullable=False),
    sa.Column('tourist_phone', sa.String(length=30), nullable=True),
    sa.Column('tourist_email', sa.String(length=120), nullable=True),
    sa.Column('messenger', sa.String(length=120), nullable=True),
    sa.Column('pax_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'ready', 'completed', 'cancelled', name='tourstatus', native_enum=False, length=20), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('guide_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('late_reported', sa.Boolean(), nullable=False),
    sa.Column('fine_decided', sa.Boolean(), nullable=False),
    sa.Column('platform_fee', sa.Integer(), nullable=False),
    sa.Column('guide_cost', sa.Integer(), nullable=False),
    sa.Column('driver_cost', sa.Integer(), nullable=False),
    sa.Column('admin_cost', sa.Integer(), nullable=False),
    sa.Column('profit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guide_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_boss_id'), 'tours', ['boss_id'], unique=False)
    op.create_index(op.f('ix_tours_driver_id'), 'tours', ['driver_id'], unique=False)
    op.create_index(op.f('ix_tours_guide_id'), 'tours', ['guide_id'], unique=False)
    op.create_index(op.f('ix_tours_start_at'), 'tours', ['start_at'], unique=False)
    op.create_index(op.f('ix_tours_status'), 'tours', ['status'], unique=False)
    op.create_index(op.f('ix_tours_title'), 'tours', ['title'], unique=False)
    op.create_table('usd_rate_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('set_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('guide', 'driver', 'admin', name='earnkind', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_boss_id'), 'earnings', ['boss_id'], unique=False)
    op.create_index(op.f('ix_earnings_tour_id'), 'earnings', ['tour_id'], unique=False)
    op.create_index(op.f('ix_earnings_user_id'), 'earnings', ['user_id'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fines_boss_id'), 'fines', ['boss_id'], unique=False)
    op.create_index(op.f('ix_fines_tour_id'), 'fines', ['tour_id'], unique=False)
    op.create_index(op.f('ix_fines_user_id'), 'fines', ['user_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guide_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tour_id')
    )
    op.create_index(op.f('ix_ratings_driver_id'), 'ratings', ['driver_id'], unique=False)
    op.create_table('tour_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('driver', 'practice', name='appkind', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'withdrawn', name='appstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tour_id', 'user_id', 'kind')
    )
    op.create_index(op.f('ix_tour_applications_tour_id'), 'tour_applications', ['tour_id'], unique=False)
    op.create_index(op.f('ix_tour_applications_user_id'), 'tour_applications', ['user_id'], unique=False)
    op.create_table('tour_cancellations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('by_user_id', sa.Integer(), nullable=False),
    sa.Column('by_admin', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_cancellations_tour_id'), 'tour_cancellations', ['tour_id'], unique=False)
    op.create_table('tour_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_stops_tour_id'), 'tour_stops', ['tour_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_stops_tour_id'), table_name='tour_stops')
    op.drop_table('tour_stops')
    op.drop_index(op.f('ix_tour_cancellations_tour_id'), table_name='tour_cancellations')
    op.drop_table('tour_cancellations')
    op.drop_index(op.f('ix_tour_applications_user_id'), table_name='tour_applications')
    op.drop_index(op.f('ix_tour_applications_tour_id'), table_name='tour_applications')
    op.drop_table('tour_applications')
    op.drop_index(op.f('ix_ratings_driver_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_fines_user_id'), table_name='fines')
    op.drop_index(op.f('ix_fines_tour_id'), table_name='fines')
    op.drop_index(op.f('ix_fines_boss_id'), table_name='fines')
    op.drop_table('fines')
    op.drop_index(op.f('ix_earnings_user_id'), table_name='earnings')
    op.drop_index(op.f('ix_earnings_tour_id'), table_name='earnings')
    op.drop_index(op.f('ix_earnings_boss_id'), table_name='earnings')
    op.drop_table('earnings')
    op.drop_table('usd_rate_log')
    op.drop_index(op.f('ix_tours_title'), table_name='tours')
    op.drop_index(op.f('ix_tours_status'), table_name='tours')
    op.drop_index(op.f('ix_tours_start_at'), table_name='tours')
    op.drop_index(op.f('ix_tours_guide_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_driver_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_boss_id'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_boss_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('guide_profiles')
    op.drop_table('driver_profiles')
    op.drop_table('boss_profiles')
    op.drop_table('boss_admins')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('level_rates')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
